server:
  port: 8090
spring:
  freemarker:
    template-loader-path: classpath:/templates/page/
    suffix: .ftl
    cache: false
    #数据库访问配置
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driverClassName: com.mysql.cj.jdbc.Driver
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://wsbsmile.top:3306/mysell?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    validationQuery: SELECT 1 FROM DUAL
  application:
    name: MySell

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-config.xml


pagehelper:
    helper-dialect: mysql
      #是否自动检测参数
    reasonable: false
    support-methods-arguments: true
    params: count=countSql

logging:
  level:
    com.app: debug
